### ISSUE TITLE
お客様向けの説明書

### ISSUE THREAD

**Issue by shoheimori** [turbou/SILRTool#3]
CSVDLツールの場合はどうやっていたかわかっていないのですが、お客様にお渡しするときに .exe と説明書.txtがあるとありがたいです。「説明書に詳細は書いてあります。」で対応できるようになります。

中身に関しては視覚的にわかると思うので、exeの提供だけでとりあえずは良いと思います。
伝えておきたい内容としては「事前準備」のところと「制限事項」となります。

[事前準備(AWS)]
1.AWS CLI  V2のインストールを済ませておく
2.AWSにログインしているユーザーのアクセスキーを予め準備しておく
3.$aws configureより前述のアクセスキーを設定してコンフィグを済ませておく

1: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
2: https://docs.aws.amazon.com/ja_jp/IAM/latest/UserGuide/id_credentials_access-keys.html
3: https://qiita.com/NorihitoYamamoto/items/badd32785078bc944089)

[事前準備(SILR Tool)]
1. [関数の読み込み]をクリックして、デプロイされているラムダ関数がリストとして現れることを確認する。
2. [設定]をクリックして、[基本設定]よりリージョン、ARN、環境変数が適切に入力されているかを確認する。Contrast UIの"サーバレス"-"設定"-"IAST解析の手順"で表れているパラメータを見比べて、入力されていない、間違っている場合は新しく書き直して[適用]-[OK]とクリックする。
※[Macで動作する場合]EXE起動時に検証不備のエラーが出る場合は、「システム設定」の「プライバシーとセキュリティ」よりこのまま開けるように調整する

[制限事項]
登録レイヤー数５（最大）となっているラムダ関数へのSILRTool経由でのレイヤー登録及び削除動作は保証しない。
複数レイヤー登録/削除中にエラーが出た場合、エラーが出るまでに行ったレイヤー登録/削除は対応され、遡久しない。

**Comment by turbou** [comment]
6415a2e21fa70dd1a168812222a8cef84980eed2
